### ISSUE TITLE
Error communicating with OpenAI

### ISSUE THREAD

**Issue by typoBro** [n3d1117/chatgpt-telegram-bot#119]
In general, I ran the bot, but the problem appeared the following message:
<img width="256" alt="Снимок экрана 2023-03-27 в 07 05 39" src="https://user-images.githubusercontent.com/114323782/227838206-13b6a467-6b20-4190-9f59-8cc994afb084.png">
It would be nice if I could get some help with this problem.

**Comment by SlvarabbitCS** [comment]
> In general, I ran the bot, but the problem appeared the following message:
> 
> <img width="256" alt="Снимок экрана 2023-03-27 в 07 05 39" src="https://user-images.githubusercontent.com/114323782/227838206-13b6a467-6b20-4190-9f59-8cc994afb084.png">
> 
> It would be nice if I could get some help with this problem. 
> 
> 

PM please

**Comment by n3d1117** [comment]
Hi @typoBro, can you share your .env file? (without api key and token)

**Comment by typoBro** [comment]
[env.txt](https://github.com/n3d1117/chatgpt-telegram-bot/files/11106299/env.txt)

**Comment by typoBro** [comment]
[same file.zip](https://github.com/n3d1117/chatgpt-telegram-bot/files/11106338/same.file.zip)

**Comment by typoBro** [comment]
Of course, here's the file:
[same file.zip](https://github.com/n3d1117/chatgpt-telegram-bot/files/11106344/same.file.zip)

**Comment by ouliusheng263** [comment]
> In general, I ran the bot, but the problem appeared the following message: <img alt="Снимок экрана 2023-03-27 в 07 05 39" width="256" src="https://user-images.githubusercontent.com/114323782/227838206-13b6a467-6b20-4190-9f59-8cc994afb084.png"> It would be nice if I could get some help with this problem.

the same problem, how to fix it ?

**Comment by SlvarabbitCS** [comment]
> > In general, I ran the bot, but the problem appeared the following message: <img alt="Снимок экрана 2023-03-27 в 07 05 39" width="256" src="https://user-images.githubusercontent.com/114323782/227838206-13b6a467-6b20-4190-9f59-8cc994afb084.png"> It would be nice if I could get some help with this problem.
> 
> 
> 
> the same problem, how to fix it ?

Send message in DM

**Comment by typoBro** [comment]
> Hi @typoBro, can you share your .env file? (without api key and token)

 I would also like to add that it has nothing to do with the API key. Because, in other projects, everything works fine. I tried a bunch of everything, even created a new account, but it did not help. So wait for help.

**Comment by typoBro** [comment]
Hello again! I'm attaching a file with an error here: [Here is the file with the error!.pdf](https://github.com/n3d1117/chatgpt-telegram-bot/files/11130139/Here.is.the.file.with.the.error.pdf) And here's the remarkable thing. I sent this error to ChatGPT and this is what he replied: 
<img width="256" alt="Снимок экрана 2023-04-01 в 20 04 03" src="https://user-images.githubusercontent.com/114323782/229304901-2a87fd59-f009-41a1-8ea0-8ea002699734.png">
**I ask the developer to check this conjecture.**

**Comment by nowiwr01w** [comment]
@n3d1117 Got the same error when tried to send the first text message. Please, can you check?

```
2023-04-02 18:12:28,366 - root - ERROR - ⚠️ _An error has occurred_ ⚠️
Error communicating with OpenAI
Traceback (most recent call last):
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 587, in arequest_raw
    result = await session.request(**request_kwargs)
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/aiohttp/connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host api.openai.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/bot/openai_helper.py", line 143, in __common_get_chat_response
    return await openai.ChatCompletion.acreate(
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 217, in acreate
    response, _, api_key = await requestor.arequest(
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 300, in arequest
    result = await self.arequest_raw(
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 604, in arequest_raw
    raise error.APIConnectionError("Error communicating with OpenAI") from e
openai.error.APIConnectionError: Error communicating with OpenAI

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/bot/telegram_bot.py", line 366, in prompt
    async for content, tokens in stream_response:
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/bot/openai_helper.py", line 92, in get_chat_response_stream
    response = await self.__common_get_chat_response(chat_id, query, stream=True)
  File "/Users/nowiwr01/Git/chatgpt-telegram-bot/bot/openai_helper.py", line 161, in __common_get_chat_response
    raise Exception(f'⚠️ _An error has occurred_ ⚠️\n{str(e)}') from e
Exception: ⚠️ _An error has occurred_ ⚠️
Error communicating with OpenAI
```

![1](https://user-images.githubusercontent.com/39140585/229358729-f62dbe12-2ca4-49b9-b5a2-6ff6f9727237.jpg)
![2](https://user-images.githubusercontent.com/39140585/229358747-1fd5d8b0-daf2-4ea1-9e64-1ff282908f44.jpg)

**Comment by neurohotep** [comment]
It helped for Mac: 
1) Search on “Certificates.command” in your Mac finder to locate the file.
2) Run it in Terminal.

**Comment by n3d1117** [comment]
Closing as it seems to be a certificates issue, see answer above or [this StackOverflow answer](https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore/57795811#57795811) for more info
