### ISSUE TITLE
Captcha detected

### ISSUE THREAD

**Issue by DJPatron** [n3d1117/chatgpt-telegram-bot#13]
I have valid email and password in my .env, my VPS IP is from Germany, my OpenAI account was registered in Germany too.
```
Beginning part three
Beginning part four
Beginning part five
Error in part five
Captcha detected
Login failed
Traceback (most recent call last):
  File "/home/ubuntu/chatgpt-telegram-bot/main.py", line 45, in <module>
    main()
  File "/home/ubuntu/chatgpt-telegram-bot/main.py", line 39, in main
    gpt3_bot = ChatGPT3Bot(config=chatgpt_config, debug=debug)
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 55, in __init__
    self.refresh_session()
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 305, in refresh_session
    raise exc
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 302, in refresh_session
    self.login(self.config["email"], self.config["password"])
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 340, in login
    raise exc
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 333, in login
    auth.begin()
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 83, in begin
    self.part_two()
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 112, in part_two
    self.part_three(token=csrf_token)
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 147, in part_three
    self.part_four(url=url)
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 181, in part_four
    self.part_five(state=state)
  File "/home/ubuntu/.local/share/virtualenvs/chatgpt-telegram-bot-HCyYIvgi/lib/python3.10/site-packages/OpenAIAuth/OpenAIAuth.py", line 219, in part_five
    raise ValueError("Captcha detected")
ValueError: Captcha detected

```

**Comment by DJPatron** [comment]
May you please add token authorisation?

**Comment by DJPatron** [comment]
Thanks, I already managed how to do it by myself just now! Thanks anyway.

**Comment by acheong08** [comment]
@n3d1117 Custom captcha solver support has been added. Documentation is still somewhat missing but you can reference 

https://github.com/acheong08/ChatGPT/blob/7fcbfab3ec9439147d232332527dbe184f9debbe/src/revChatGPT/__main__.py#L10-L34

**Comment by acheong08** [comment]
Which is passed here:
https://github.com/acheong08/ChatGPT/blob/7fcbfab3ec9439147d232332527dbe184f9debbe/src/revChatGPT/__main__.py#L95-L96

**Comment by n3d1117** [comment]
Thanks @acheong08
