### ISSUE TITLE
Can't run bot on mac

### ISSUE THREAD

**Issue by emushtat** [n3d1117/chatgpt-telegram-bot#148]
$ python bot/main.py 
Traceback (most recent call last):
  File "bot/main.py", line 6, in <module>
    from openai_helper import OpenAIHelper, default_max_tokens
  File "/chatgpt-telegram-bot/bot/openai_helper.py", line 29, in <module>
    class OpenAIHelper:
  File "/chatgpt-telegram-bot/bot/openai_helper.py", line 45, in OpenAIHelper
    def get_conversation_stats(self, chat_id: int) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable

**Comment by AlexHTW** [comment]
What python version are you running? Looks similar to this issue #90

**Comment by n3d1117** [comment]
Yes, you need python 3.9 @emushtat
