### ISSUE TITLE
login failed

### ISSUE THREAD

**Issue by ZhaoTing1993** [n3d1117/chatgpt-telegram-bot#16]
yesterday i succussfully run this project, but today i found my lost the connection. (In my country internet is not that good :<)
so i reboot my process, i found this login failed error:

"Auth0 did not issue an access token"
```Traceback (most recent call last):
  File "C:\Users\ting\anaconda3\envs\py310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 309, in part_seven
    self.part_eight(old_state=state, new_state=new_state)
  File "C:\Users\ting\anaconda3\envs\py310\lib\site-packages\OpenAIAuth\OpenAIAuth.py", line 363, in part_eight
    raise Exception("Auth0 did not issue an access token")
Exception: Auth0 did not issue an access token
```

but i have checked my account & password that is correct, and could successfully login in Chrome browser.
after retried run main.py for 2times, i found this:
"Exception: You have been rate limited."

```Debugger enabled on OpenAIAuth
Beginning auth process
Beginning part two
Beginning part three
You have been rate limited
Login failed
Traceback (most recent call last):
  File "/app/main.py", line 46, in <module>
    main()
  File "/app/main.py", line 40, in main
    gpt3_bot = ChatGPT3Bot(config=chatgpt_config, debug=debug)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 59, in __init__
    self.refresh_session()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 309, in refresh_session
    raise exc
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.10/site-packages/asyncChatGPT/asyncChatGPT.py", line 306, in refresh_session
    self.login(self.config["email"], self.config["password"])
```

**Comment by nailuoGG** [comment]
Take it easy and wait for five minutes to see if it works.

Alternatively, you can try signing in at https://chat.openai.com/ to see if it works.

**Comment by n3d1117** [comment]
Hi @ZhaoTing1993, authentication is handled by [acheong08/ChatGPT](https://github.com/acheong08/ChatGPT), so you should open an issue there!
