### ISSUE TITLE
"The token XYZ was rejected by the server"

### ISSUE THREAD

**Issue by GuillaumeMoscou** [n3d1117/chatgpt-telegram-bot#168]
Hi,

I have installed the chatgpt-telegram-bot on my Ubuntu VPS using the Docker container provided here.

I ran the following commands:

 `sudo docker pull ghcr.io/n3d1117/chatgpt-telegram-bot:latest` 
 
 then 
 
`sudo docker run --env-file=/home/my_path/.env -d --name chatgpt_telegram_bot ghcr.io/n3d1117/chatgpt-telegram-bot:latest`

However, the bot stopped immediately after starting.

When I checked the logs, it showed the following error message:

```
Traceback (most recent call last):
  File "/app/bot/main.py", line 72, in <module>
    main()
  File "/app/bot/main.py", line 68, in main
    telegram_bot.run()
  File "/app/bot/telegram_bot.py", line 780, in run
    application.run_polling()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 725, in run_polling
    return self.__run(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 919, in __run
    raise exc
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 908, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 397, in initialize
    await self.bot.initialize()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 258, in initialize
    await super().initialize()
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 583, in initialize
    raise InvalidToken(f"The token `{self._token}` was rejected by the server.") from exc
telegram.error.InvalidToken: The token `"xxxxxxx"` was rejected by the server.
```

This is very strange because my Telegram token is valid. I ran the chatgpt-telegram-bot locally on my PC (without Docker) and it works fine using the same .env file that I used previously.

Even if I create a new Telegram bot with a new token, it doesn't resolve the issue.

Thank you for any comments on this.

**Comment by AlexHTW** [comment]
Hey @GuillaumeMoscou, `docker run` is not on friendly terms with quotes in .env files. I will open an issue on this.
For now you will need to use one .env file for usage without docker or with `docker compose up` and another .env file for usage with `docker run`. In the `docker run` .env file you have to remove all quotation marks.

**Comment by GuillaumeMoscou** [comment]
Thank you very much for your help, it works perfectly with a docker-compose up 👍
