### ISSUE TITLE
OpenAIHelper

### ISSUE THREAD

**Issue by genocid515** [n3d1117/chatgpt-telegram-bot#173]
(venv) root@ruvds-y8afp:~/chatgpt-telegram-bot# python bot/main.py
Traceback (most recent call last):
  File "bot/main.py", line 6, in <module>
    from openai_helper import OpenAIHelper, default_max_tokens
  File "/root/chatgpt-telegram-bot/bot/openai_helper.py", line 29, in <module>
    class OpenAIHelper:
  File "/root/chatgpt-telegram-bot/bot/openai_helper.py", line 45, in OpenAIHelper
    def get_conversation_stats(self, chat_id: int) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable

**Comment by AlexHTW** [comment]
Hi @genocid515,
see issue #90, python 3.9 is required to run the bot.
