### ISSUE TITLE
cannot import name 'ApplicationBuilder' from 'telegram.ext'

### ISSUE THREAD

**Issue by khanfar** [n3d1117/chatgpt-telegram-bot#224]
please help , i restart the pc and i cant run the bot , here is the issue :     C:\Users\Lenovo\Downloads\Compressed\chatgpt-telegram-bot-main\chatgpt-telegram-bot-main\bot>python main.py
Traceback (most recent call last):
  File "C:\Users\Lenovo\Downloads\Compressed\chatgpt-telegram-bot-main\chatgpt-telegram-bot-main\bot\main.py", line 7, in <module>
    from telegram_bot import ChatGPTTelegramBot
  File "C:\Users\Lenovo\Downloads\Compressed\chatgpt-telegram-bot-main\chatgpt-telegram-bot-main\bot\telegram_bot.py", line 12, in <module>
    from telegram.ext import ApplicationBuilder, ContextTypes, CommandHandler, MessageHandler, \
ImportError: cannot import name 'ApplicationBuilder' from 'telegram.ext' (C:\Python311\Lib\site-packages\telegram\ext\__init__.py)

**Comment by khanfar** [comment]
i got it .. i do   pip install --upgrade python-telegram-bot ... every thing works now ...
