### ISSUE TITLE
Help me fix this please

### ISSUE THREAD

**Issue by nevzra** [n3d1117/chatgpt-telegram-bot#25]
![Screenshot_20221212-081503275](https://user-images.githubusercontent.com/119541699/206941594-74afc5b7-54c0-496a-8d2e-d8d021bc74ce.jpg)

**Comment by nailuoGG** [comment]
https://github.com/acheong08/ChatGPT/issues/261

**Comment by xBabylonia** [comment]
same, me too
![image](https://user-images.githubusercontent.com/116042240/206960850-44e83dec-4e3d-43c2-a316-dfcfaa238402.png)

**Comment by G-Sea** [comment]
same as you：（

**Comment by G-Sea** [comment]
This may be helpful to the author
https://github.com/acheong08/ChatGPT/wiki/Setup

**Comment by xBabylonia** [comment]
work using this "pip3 install revChatGPT==0.0.a42"

**Comment by n3d1117** [comment]
@channon6 @nailuoGG @xBabylonia @G-Sea Please test the [experimental-cloudflare-playwright](https://github.com/n3d1117/chatgpt-telegram-bot/tree/experimental-cloudflare-playwright) branch.

Note that it requires Firefox headless browser for playwright, so before starting make sure to run:
```bash
playwright install firefox
```

**Comment by waltcow** [comment]
Just test the [experimental-cloudflare-playwright](https://github.com/n3d1117/chatgpt-telegram-bot/tree/experimental-cloudflare-playwright) branch. 

can you provide some instruction here @n3d1117 , 

```shell

(chatgpt-telegram-bot) root@hostDare:/opt/chatgpt-telegram-bot# python3 main.py
Traceback (most recent call last):
  File "/opt/chatgpt-telegram-bot/main.py", line 80, in <module>
    main()
  File "/opt/chatgpt-telegram-bot/main.py", line 51, in main
    session_token, cf_clearance, user_agent = extract_openai_tokens(
  File "/opt/chatgpt-telegram-bot/main.py", line 18, in extract_openai_tokens
    page.get_by_role("button", name="Log in").click()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-pAzyne2v/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 13670, in click
    self._sync(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-pAzyne2v/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 104, in _sync
    return task.result()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-pAzyne2v/lib/python3.10/site-packages/playwright/_impl/_locator.py", line 146, in click
    return await self._frame.click(self._selector, strict=True, **params)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-pAzyne2v/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 489, in click
    await self._channel.send("click", locals_to_params(locals()))
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-pAzyne2v/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 44, in send
    return await self._connection.wrap_api_call(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-pAzyne2v/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 419, in wrap_api_call
    return await cb()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-pAzyne2v/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 79, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_role("button", name="Log in")
============================================================
(chatgpt-telegram-bot) root@hostDare:/opt/chatgpt-telegram-bot#

```

**Comment by n3d1117** [comment]
@waltcow OpenAI is currently down for me, try again in a while

<img width="864" alt="Screenshot 2022-12-12 at 16 10 55" src="https://user-images.githubusercontent.com/11541888/207080970-1e8ece33-2d4c-4f50-a7ca-277abf6e3053.png">

**Comment by waltcow** [comment]
<img width="1764" alt="image" src="https://user-images.githubusercontent.com/3941174/207083516-54a12afe-6872-4037-8524-5559b71f007d.png">

**Comment by waltcow** [comment]
still not working 😭 @n3d1117

**Comment by xBabylonia** [comment]
> still not working 😭 @n3d1117

death rn

**Comment by n3d1117** [comment]
Now updated to the official APIs! Closing this
