### ISSUE TITLE
Getting  `Failed to get response ⚠️ An error has occurred. ⚠️ Invalid response object from API: '400 Bad Request' (HTTP response code was 400)`

### ISSUE THREAD

**Issue by Mr-Nobody1** [n3d1117/chatgpt-telegram-bot#328]
```
Traceback (most recent call last):
  File "C:\Users\Ammad Ali\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\venv\Lib\site-packages\openai\api_requestor.py", line 331, in handle_error_response
    error_data = resp["error"]
                 ~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\bot\openai_helper.py", line 170, in __common_get_chat_response
    return await openai.ChatCompletion.acreate(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\venv\Lib\site-packages\openai\api_resources\chat_completion.py", line 45, in acreate
    return await super().acreate(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Usersi\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\venv\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 217, in acreate    
    response, _, api_key = await requestor.arequest(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Use\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\venv\Lib\site-packages\openai\api_requestor.py", line 310, in arequest
    resp, got_stream = await self._interpret_async_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\venv\Lib\site-packages\openai\api_requestor.py", line 646, in _interpret_async_response
    self._interpret_response_line(
  File "C:\Users\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\venv\Lib\site-packages\openai\api_requestor.py", line 683, in _interpret_response_line
    raise self.handle_error_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\venv\Lib\site-packages\openai\api_requestor.py", line 333, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '400 Bad Request' (HTTP response code was 400)

The above exception was the direct cause of the following exception:

  File "C:\Users\\Documents\Python\telegram bots\SC\chatgpt-telegram-bot\bot\openai_helper.py", line 188, in __common_get_chat_response
    raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
Exception: ⚠️ _An error has occurred._ ⚠️
Invalid response object from API: '400 Bad Request' (HTTP response code was 400)
```

Assistant prompt is on! Hou can I fix this Thanks

**Comment by n3d1117** [comment]
Seems to be an issue with the [openai-python](https://github.com/openai/openai-python) library
