### ISSUE TITLE
Problems with special characters (german Ö, Ä, and Ü) at .env file

### ISSUE THREAD

**Issue by wlanowski** [n3d1117/chatgpt-telegram-bot#423]
Hi there,

i wanted to use a own assistent prompt for my bot. I wanted to use the german word "persönlich" which has the special char ö. With this char in the .env file it is not possible to compose my bot via docker compose.

Here is the log info, if you want to compose the docker container with special chars:

`chat-martha-chatgpt-telegram-bot-1  | Traceback (most recent call last):
chat-martha-chatgpt-telegram-bot-1  |   File "/app/bot/main.py", line 100, in <module>
chat-martha-chatgpt-telegram-bot-1  |     main()
chat-martha-chatgpt-telegram-bot-1  |   File "/app/bot/main.py", line 13, in main
chat-martha-chatgpt-telegram-bot-1  |     load_dotenv()
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/main.py", line 346, in load_dotenv
chat-martha-chatgpt-telegram-bot-1  |     return dotenv.set_as_environment_variables()
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/main.py", line 91, in set_as_environment_variables
chat-martha-chatgpt-telegram-bot-1  |     if not self.dict():
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/main.py", line 75, in dict
chat-martha-chatgpt-telegram-bot-1  |     self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/main.py", line 233, in resolve_variables
chat-martha-chatgpt-telegram-bot-1  |     for (name, value) in values:
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/main.py", line 83, in parse
chat-martha-chatgpt-telegram-bot-1  |     for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/main.py", line 25, in with_warn_for_invalid_lines
chat-martha-chatgpt-telegram-bot-1  |     for mapping in mappings:
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/parser.py", line 173, in parse_stream
chat-martha-chatgpt-telegram-bot-1  |     reader = Reader(stream)
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/site-packages/dotenv/parser.py", line 64, in __init__
chat-martha-chatgpt-telegram-bot-1  |     self.string = stream.read()
chat-martha-chatgpt-telegram-bot-1  |   File "/usr/local/lib/python3.9/codecs.py", line 322, in decode
chat-martha-chatgpt-telegram-bot-1  |     (result, consumed) = self._buffer_decode(data, self.errors, final)
chat-martha-chatgpt-telegram-bot-1  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 796: invalid start byte
`

**Comment by n3d1117** [comment]
Hey @wlanowski, I just tried to start the bot with `ASSISTANT_PROMPT=persönlich` in my `.env` and I didn't have any issue. Could you make sure that your .env file is saved with UTF-8 encoding?
