### ISSUE TITLE
Problem with installing

### ISSUE THREAD

**Issue by letsmont** [n3d1117/chatgpt-telegram-bot#424]
Hi, I've tried installing your bot and failed everytime. I give you a full information on what I am doing:
I've acquired a VPS machine from hetzner.com with Ubuntu 20 OS. I am accessing the machine via ssh with root username and password. 
1. After updating and upgrading the machine I first cloned the repo into the machine using this command and navigated to the directory: 
git clone https://github.com/n3d1117/chatgpt-telegram-bot.git
cd chatgpt-telegram-bot

2. Then I edited the .env.example file and changed its name to .env. here is the content of it: 

# Your OpenAI API key
OPENAI_API_KEY=sk-

# Your Telegram bot token obtained using @BotFather
TELEGRAM_BOT_TOKEN=

# Telegram user ID of admins, or - to assign no admin
ADMIN_USER_IDS=

# Comma separated list of telegram user IDs, or * to allow all
ALLOWED_TELEGRAM_USER_IDS=

# Optional configuration, refer to the README for more details
 BUDGET_PERIOD=monthly
 USER_BUDGETS=3.0
 GUEST_BUDGET=1.0
 TOKEN_PRICE=0.01
 IMAGE_PRICES=0.08,0.09,0.1
 TRANSCRIPTION_PRICE=0.030
 ENABLE_QUOTING=true
 ENABLE_IMAGE_GENERATION=true
 ENABLE_TRANSCRIPTION=true
 PROXY=http://localhost:8080
 OPENAI_MODEL=gpt-4
 ASSISTANT_PROMPT="You are a helpful assistant."
 SHOW_USAGE=true
 STREAM=true
 MAX_TOKENS=2000
 MAX_HISTORY_SIZE=15
 MAX_CONVERSATION_AGE_MINUTES=180
 VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true
 VOICE_REPLY_PROMPTS="Hi bot;Hey bot;Hi chat;Hey chat"
 N_CHOICES=1
 TEMPERATURE=1.0
 PRESENCE_PENALTY=0.0
 FREQUENCY_PENALTY=0.0
 IMAGE_SIZE=1024x1024
 GROUP_TRIGGER_KEYWORD="Hey GPT"
 IGNORE_GROUP_TRANSCRIPTIONS=true
 BOT_LANGUAGE=en
 ENABLE_FUNCTIONS=true
 PLUGINS=weather,ddg_web_search,ddg_translate,ddg_image_search,crypto,whois
 
 3. After that I used this code: 
 
 Docker-compose up
 
 some files downloaded and i got this message: 

WARNING: Image for service chatgpt-telegram-bot was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating chatgpt-telegram-bot_chatgpt-telegram-bot_1 ... done
Attaching to chatgpt-telegram-bot_chatgpt-telegram-bot_1

and after this some messages were shown to me which in start of the lines "chatgpt-telegram-bot_1" was shown with blue color. 

chatgpt-telegram-bot_1  |   | exceptiongroup.ExceptionGroup: multiple connection attempts failed (2 sub-exceptions)
chatgpt-telegram-bot_1  |   +-+---------------- 1 ----------------
chatgpt-telegram-bot_1  |     | Traceback (most recent call last):
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 168, in try_connect
chatgpt-telegram-bot_1  |     |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2202, in connect_tcp
chatgpt-telegram-bot_1  |     |     await get_running_loop().create_connection(
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
chatgpt-telegram-bot_1  |     |     raise exceptions[0]
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
chatgpt-telegram-bot_1  |     |     sock = await self._connect_sock(
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
chatgpt-telegram-bot_1  |     |     await self.sock_connect(sock, address)
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
chatgpt-telegram-bot_1  |     |     return await fut
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 505, in _sock_connect
chatgpt-telegram-bot_1  |     |     sock.connect(address)
chatgpt-telegram-bot_1  |     | OSError: [Errno 99] Address not available
chatgpt-telegram-bot_1  |     +---------------- 2 ----------------
chatgpt-telegram-bot_1  |     | Traceback (most recent call last):
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 168, in try_connect
chatgpt-telegram-bot_1  |     |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2202, in connect_tcp
chatgpt-telegram-bot_1  |     |     await get_running_loop().create_connection(
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
chatgpt-telegram-bot_1  |     |     raise exceptions[0]
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
chatgpt-telegram-bot_1  |     |     sock = await self._connect_sock(
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
chatgpt-telegram-bot_1  |     |     await self.sock_connect(sock, address)
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
chatgpt-telegram-bot_1  |     |     return await fut
chatgpt-telegram-bot_1  |     |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
chatgpt-telegram-bot_1  |     |     raise OSError(err, f'Connect call failed {address}')
chatgpt-telegram-bot_1  |     | ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080)
chatgpt-telegram-bot_1  |     +------------------------------------
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | The above exception was the direct cause of the following exception:
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | Traceback (most recent call last):
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
chatgpt-telegram-bot_1  |     yield
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
chatgpt-telegram-bot_1  |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 230, in connect_tcp
chatgpt-telegram-bot_1  |     raise OSError("All connection attempts failed") from cause
chatgpt-telegram-bot_1  | OSError: All connection attempts failed
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | The above exception was the direct cause of the following exception:
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | Traceback (most recent call last):
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
chatgpt-telegram-bot_1  |     yield
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
chatgpt-telegram-bot_1  |     resp = await self._pool.handle_async_request(req)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
chatgpt-telegram-bot_1  |     raise exc
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
chatgpt-telegram-bot_1  |     response = await connection.handle_async_request(request)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http_proxy.py", line 271, in handle_async_request
chatgpt-telegram-bot_1  |     connect_response = await self._connection.handle_async_request(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
chatgpt-telegram-bot_1  |     raise exc
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
chatgpt-telegram-bot_1  |     stream = await self._connect(request)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 117, in _connect
chatgpt-telegram-bot_1  |     stream = await self._network_backend.connect_tcp(**kwargs)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
chatgpt-telegram-bot_1  |     return await self._backend.connect_tcp(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 121, in connect_tcp
chatgpt-telegram-bot_1  |     stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
chatgpt-telegram-bot_1  |     self.gen.throw(typ, value, traceback)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
chatgpt-telegram-bot_1  |     raise to_exc(exc) from exc
chatgpt-telegram-bot_1  | httpcore.ConnectError: All connection attempts failed
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | The above exception was the direct cause of the following exception:
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | Traceback (most recent call last):
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
chatgpt-telegram-bot_1  |     res = await self._client.request(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1530, in request
chatgpt-telegram-bot_1  |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
chatgpt-telegram-bot_1  |     response = await self._send_handling_auth(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
chatgpt-telegram-bot_1  |     response = await self._send_handling_redirects(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
chatgpt-telegram-bot_1  |     response = await self._send_single_request(request)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
chatgpt-telegram-bot_1  |     response = await transport.handle_async_request(request)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
chatgpt-telegram-bot_1  |     resp = await self._pool.handle_async_request(req)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
chatgpt-telegram-bot_1  |     self.gen.throw(typ, value, traceback)
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
chatgpt-telegram-bot_1  |     raise mapped_exc(message) from exc
chatgpt-telegram-bot_1  | httpx.ConnectError: All connection attempts failed
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | The above exception was the direct cause of the following exception:
chatgpt-telegram-bot_1  |
chatgpt-telegram-bot_1  | Traceback (most recent call last):
chatgpt-telegram-bot_1  |   File "/app/bot/main.py", line 100, in <module>
chatgpt-telegram-bot_1  |     main()
chatgpt-telegram-bot_1  |   File "/app/bot/main.py", line 96, in main
chatgpt-telegram-bot_1  |     telegram_bot.run()
chatgpt-telegram-bot_1  |   File "/app/bot/telegram_bot.py", line 807, in run
chatgpt-telegram-bot_1  |     application.run_polling()
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 727, in run_polling
chatgpt-telegram-bot_1  |     return self.__run(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 921, in __run
chatgpt-telegram-bot_1  |     raise exc
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 910, in __run
chatgpt-telegram-bot_1  |     loop.run_until_complete(self.initialize())
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
chatgpt-telegram-bot_1  |     return future.result()
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 399, in initialize
chatgpt-telegram-bot_1  |     await self.bot.initialize()
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 271, in initialize
chatgpt-telegram-bot_1  |     await super().initialize()
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 591, in initialize
chatgpt-telegram-bot_1  |     await self.get_me()
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 1706, in get_me
chatgpt-telegram-bot_1  |     return await super().get_me(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 381, in decorator
chatgpt-telegram-bot_1  |     result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 736, in get_me
chatgpt-telegram-bot_1  |     result = await self._post(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 469, in _post
chatgpt-telegram-bot_1  |     return await self._do_post(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 325, in _do_post
chatgpt-telegram-bot_1  |     return await super()._do_post(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 497, in _do_post
chatgpt-telegram-bot_1  |     return await request.post(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 168, in post
chatgpt-telegram-bot_1  |     result = await self._request_wrapper(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 291, in _request_wrapper
chatgpt-telegram-bot_1  |     raise exc
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 277, in _request_wrapper
chatgpt-telegram-bot_1  |     code, payload = await self.do_request(
chatgpt-telegram-bot_1  |   File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 240, in do_request
chatgpt-telegram-bot_1  |     raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
chatgpt-telegram-bot_1  | telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed

above is the full message after that previous message. 

4. I tired to go from the other method instead used these:

docker pull n3d1117/chatgpt-telegram-bot:latest
docker run -it --env-file .env n3d1117/chatgpt-telegram-bot

and I got these: 

root@ubuntu-2gb-fsn1-1:~/chatgpt-telegram-bot# docker run -it --env-file .env n3d1117/chatgpt-telegram-bot
anyio._backends._asyncio.ExceptionGroup: 2 exceptions were raised in the task group:
----------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 167, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1627, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 505, in _sock_connect
    sock.connect(address)
OSError: [Errno 99] Address not available
----------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 167, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1627, in connect_tcp
    await get_running_loop().create_connection(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 8080)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 225, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http_proxy.py", line 271, in handle_async_request
    connect_response = await self._connection.handle_async_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 117, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 121, in connect_tcp
    stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    res = await self._client.request(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bot/main.py", line 99, in <module>
    main()
  File "/app/bot/main.py", line 95, in main
    telegram_bot.run()
  File "/app/bot/telegram_bot.py", line 790, in run
    application.run_polling()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 727, in run_polling
    return self.__run(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 921, in __run
    raise exc
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 910, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_application.py", line 399, in initialize
    await self.bot.initialize()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 271, in initialize
    await super().initialize()
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 591, in initialize
    await self.get_me()
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 1706, in get_me
    return await super().get_me(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 381, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 736, in get_me
    result = await self._post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 469, in _post
    return await self._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/ext/_extbot.py", line 325, in _do_post
    return await super()._do_post(
  File "/usr/local/lib/python3.9/site-packages/telegram/_bot.py", line 497, in _do_post
    return await request.post(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 291, in _request_wrapper
    raise exc
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_baserequest.py", line 277, in _request_wrapper
    code, payload = await self.do_request(
  File "/usr/local/lib/python3.9/site-packages/telegram/request/_httpxrequest.py", line 240, in do_request
    raise NetworkError(f"httpx.{err.__class__.__name__}: {err}") from err
telegram.error.NetworkError: httpx.ConnectError: All connection attempts failed

I don't know where I'm going wrong or what is the problem because unfortunetly I'm no expert in this area and wanted to have this bot completly out of hobby and curiosity. so I hope you can help me solve my issue. 
Thank you very much in advance.

**Comment by n3d1117** [comment]
Hi @letsmont, try deleting everything under optional configuration and run again.
Seem to be a duplicate of #105, #81 and #97

**Comment by letsmont** [comment]
Great! it worked by just deleting the proxy line! thank you.
