### ISSUE TITLE
Cannot use model gpt-4

### ISSUE THREAD

**Issue by rexkani** [n3d1117/chatgpt-telegram-bot#434]
i'm getting below error when i try to send any message by telegram:

`2023-09-23 08:09:47,421 - httpx - INFO - HTTP Request: POST https://api.telegram.org/#masked#/getMe "HTTP/1.1 200 OK"
2023-09-23 08:09:47,782 - httpx - INFO - HTTP Request: POST https://api.telegram.org/#masked#/setMyCommands "HTTP/1.1 200 OK"
2023-09-23 08:09:47,977 - httpx - INFO - HTTP Request: POST https://api.telegram.org/#masked#/deleteWebhook "HTTP/1.1 200 OK"
2023-09-23 08:09:47,978 - telegram.ext.Application - INFO - Application started
2023-09-23 08:09:56,067 - httpx - INFO - HTTP Request: POST https://api.telegram.org/#masked#/getUpdates "HTTP/1.1 200 OK"
2023-09-23 08:09:56,069 - root - INFO - New message received from user @CeteaXXX
2023-09-23 08:09:56,786 - httpx - INFO - HTTP Request: POST https://api.telegram.org/#masked#/sendChatAction "HTTP/1.1 200 OK"
2023-09-23 08:09:59,145 - root - ERROR - __count_tokens() is not presently implemented for model gpt-4
Traceback (most recent call last):
  File "/app/bot/openai_helper.py", line 42, in get_chat_response
    token_count = self.__count_tokens(self.conversations[chat_id])
  File "/app/bot/openai_helper.py", line 204, in __count_tokens
    raise NotImplementedError(f"__count_tokens() is not presently implemented for model {model}")
NotImplementedError: __count_tokens() is not presently implemented for model gpt-4
2023-09-23 08:09:59,330 - httpx - INFO - HTTP Request: POST https://api.telegram.org/#masked#/sendMessage "HTTP/1.1 400 Bad Request"
2023-09-23 08:10:06,251 - httpx - INFO - HTTP Request: POST https://api.telegram.org/#masked#/getUpdates "HTTP/1.1 200 OK"`

**Comment by n3d1117** [comment]
Hey @rexkani, I think you have an old version of the bot. Can you make sure you're up to date with the latest release?

**Comment by rexkani** [comment]
i pulled n3d1117/chatgpt-telegram-bot:latest from dockerhub

**Comment by rexkani** [comment]
Hi, @n3d1117 i even just try to manually build the image and it still doesn't work... with the same error message.

**Comment by rexkani** [comment]
yes i guess it's my problem. i have abondoned my old RancherOS environment and migrated to an ubuntu environment and deploy again, and it's working now.

Thanks for your hint.
