### ISSUE TITLE
MAX_TOKENS gpt-4-1106-preview issues

### ISSUE THREAD

**Issue by madnexus** [n3d1117/chatgpt-telegram-bot#455]
Looks like the new gpt-4-1106-preview model is having issues with the MAX_TOKENS variable.

Not setting the variable exited with code 1:

```
Traceback (most recent call last):
File "/app/bot/main.py", line 99, in <module>
    main()
   File "/app/bot/main.py", line 41, in main
    'max_tokens': int(os.environ.get('MAX_TOKENS', max_tokens_default)),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

And setting the variable to a limit returns:

```
 2023-11-08 07:42:34,195 - root - ERROR - ⚠️ _An error has occurred._ ⚠️
 num_tokens_from_messages() is not implemented for model gpt-4-1106-preview.
 Traceback (most recent call last):
   File "/app/bot/openai_helper.py", line 215, in __common_get_chat_response
     token_count = self.__count_tokens(self.conversations[chat_id])
   File "/app/bot/openai_helper.py", line 437, in __count_tokens
     raise NotImplementedError(f"""num_tokens_from_messages() is not implemented for model {model}.""")
 NotImplementedError: num_tokens_from_messages() is not implemented for model gpt-4-1106-preview.
 
 The above exception was the direct cause of the following exception:
 
 Traceback (most recent call last):
   File "/app/bot/telegram_bot.py", line 407, in prompt
     async for content, tokens in stream_response:
   File "/app/bot/openai_helper.py", line 162, in get_chat_response_stream
     response = await self.__common_get_chat_response(chat_id, query, stream=True)
   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
     return await fn(*args, **kwargs)
   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
     do = self.iter(retry_state=retry_state)
   File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
     return fut.result()
   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
     return self.__get_result()
   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
     raise self._exception
   File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
     result = await fn(*args, **kwargs)
   File "/app/bot/openai_helper.py", line 257, in __common_get_chat_response
     raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
 Exception: ⚠️ _An error has occurred._ ⚠️
 num_tokens_from_messages() is not implemented for model gpt-4-1106-preview.
 2023-11-08 07:42:34,215 - root - ERROR - Exception while handling an update: Can't parse entities: can't find end of the entity starting at byte offset 77
```

Thank you!

**Comment by AlexHTW** [comment]
Hey! 
The new model has not been added to the main branch yet.
You can checkout #448 to use the preview model.

**Comment by n3d1117** [comment]
@cedlap Done! Closing this now
