### ISSUE TITLE
support for gpt-4-1106-preview?

### ISSUE THREAD

**Issue by darknate** [n3d1117/chatgpt-telegram-bot#467]
Hi! I'm trying to set up a new model, but I can't understand why it is not working. I see that this model was on the list of supported models for a long time, but I suppose something changed with the release.

I have this error (before I resolved other errors with defaults):

```
2023-11-21 16:32:30,256 - root - ERROR - ⚠️ _An error has occurred._ ⚠️
num_tokens_from_messages() is not implemented for model gpt-4-1106-preview.
Traceback (most recent call last):
  File "/app/bot/openai_helper.py", line 215, in __common_get_chat_response
    token_count = self.__count_tokens(self.conversations[chat_id])
  File "/app/bot/openai_helper.py", line 437, in __count_tokens
    raise NotImplementedError(f"""num_tokens_from_messages() is not implemented for model {model}.""")
NotImplementedError: num_tokens_from_messages() is not implemented for model gpt-4-1106-preview.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/bot/telegram_bot.py", line 407, in prompt
    async for content, tokens in stream_response:
  File "/app/bot/openai_helper.py", line 162, in get_chat_response_stream
    response = await self.__common_get_chat_response(chat_id, query, stream=True)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 88, in async_wrapped
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 47, in __call__
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/tenacity/_asyncio.py", line 50, in __call__
    result = await fn(*args, **kwargs)
  File "/app/bot/openai_helper.py", line 257, in __common_get_chat_response
    raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
Exception: ⚠️ _An error has occurred._ ⚠️
num_tokens_from_messages() is not implemented for model gpt-4-1106-preview.
```

It looks like the code can't find default values for this model because it hadn't resolved some other options like `MAX_TOKENS` before I set them in the .env file. Will be grateful for this help, because new model works awesome.

**Comment by n3d1117** [comment]
Hi @darknate, could you make sure that you're the latest version of the project by doing a `git pull`?

Also, please consider sharing relevant parts of your `.env` file so we can understand it better

**Comment by Jake-double-one** [comment]
@darknate 
Unfortunately, all the latest models are not supported by the bot:
https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo
You can only use "gpt-4" and currently, we need to wait until "gpt-4-1106-preview" becomes "gpt-4".

**Comment by DiscipulusVitae** [comment]
> Hi @darknate, could you make sure that you're the latest version of the project by doing a `git pull`?
> 
> Also, please consider sharing relevant parts of your `.env` file so we can understand it better

Hi! Are you going to continue this bot? gpt-4-turbo has been realsed (gpt-4-turbo-2024-04-09).
```
\bot\openai_helper.py", line 274, in __common_get_chat_response
    raise Exception(f"⚠️ _{localized_text('error', bot_language)}._ ⚠️\n{str(e)}") from e
Exception: ⚠️ _An error has occurred._ ⚠️
num_tokens_from_messages() is not implemented for model gpt-4-turbo-2024-04-09.
```
env file:
```
# Your OpenAI API key
OPENAI_API_KEY=#{my_api_key}

# Your Telegram bot token obtained using @BotFather
TELEGRAM_BOT_TOKEN=#{my_bot_token}

# Telegram user ID of admins, or - to assign no admin
ADMIN_USER_IDS=-

# Comma separated list of telegram user IDs, or * to allow all
ALLOWED_TELEGRAM_USER_IDS=#{my_telegram_user_id}

# Optional configuration, refer to the README for more details
# BUDGET_PERIOD=monthly
# USER_BUDGETS=*
# GUEST_BUDGET=100.0
# TOKEN_PRICE=0.002
# IMAGE_PRICES=0.016,0.018,0.02
# TRANSCRIPTION_PRICE=0.006
# VISION_TOKEN_PRICE=0.01
# ENABLE_QUOTING=true
# ENABLE_IMAGE_GENERATION=true
# ENABLE_TTS_GENERATION=true
# ENABLE_TRANSCRIPTION=true
# ENABLE_VISION=true
# PROXY=http://localhost:8080
OPENAI_MODEL=gpt-4-turbo-2024-04-09
# OPENAI_BASE_URL=https://example.com/v1/
# ASSISTANT_PROMPT="You are a helpful assistant."
# SHOW_USAGE=false
# STREAM=true
MAX_TOKENS=1200
# VISION_MAX_TOKENS=300
# MAX_HISTORY_SIZE=15
# MAX_CONVERSATION_AGE_MINUTES=180
# VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true
# VOICE_REPLY_PROMPTS="Hi bot;Hey bot;Hi chat;Hey chat"
# VISION_PROMPT="What is in this image"
# N_CHOICES=1
# TEMPERATURE=1.0
# PRESENCE_PENALTY=0.0
# FREQUENCY_PENALTY=0.0
# IMAGE_MODEL=dall-e-3
# IMAGE_QUALITY=hd
# IMAGE_STYLE=natural
# IMAGE_SIZE=1024x1024
# IMAGE_FORMAT=document
# VISION_DETAIL="low"
# GROUP_TRIGGER_KEYWORD=""
# IGNORE_GROUP_TRANSCRIPTIONS=true
# IGNORE_GROUP_VISION=true
# TTS_MODEL="tts-1"
# TTS_VOICE="alloy"
# TTS_PRICES=0.015,0.030
# BOT_LANGUAGE=en
# ENABLE_VISION_FOLLOW_UP_QUESTIONS="true"
# VISION_MODEL="gpt-4-vision-preview"
```
