### ISSUE TITLE
HTTPError with web search plugin

### ISSUE THREAD

**Issue by bsima** [n3d1117/chatgpt-telegram-bot#490]
Any time I try to use the web plugin, I get an error like this:

```
2023-12-11 15:25:36,709 - root - INFO - Calling function web_search with arguments {"query":"best tourist destinations in England 2023","region":"uk-en"}
2023-12-11 15:25:37,108 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:40,193 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:43,277 - duckduckgo_search.duckduckgo_search - WARNING - _get_url() https://links.duckduckgo.com/d.js HTTPError 
2023-12-11 15:25:43,278 - root - ERROR - 
Traceback (most recent call last):
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/telegram_bot.py", line 693, in prompt
    async for content, tokens in stream_response:
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/openai_helper.py", line 178, in get_chat_response_stream
    response, plugins_used = await self.__handle_function_call(chat_id, response, stream=True)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/openai_helper.py", line 304, in __handle_function_call
    function_response = await self.plugin_manager.call_function(function_name, self, arguments)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/plugin_manager.py", line 59, in call_function
    return json.dumps(await plugin.execute(function_name, helper, **json.loads(arguments)), default=str)
  File "/home/ben/src/n3d1117/chatgpt-telegram-bot/bot/plugins/ddg_web_search.py", line 56, in execute
    results = list(islice(ddgs_gen, 3))
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 150, in text
    yield from self._text_api(keywords, region, safesearch, timelimit)
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 201, in _text_api
    resp = self._get_url(
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 89, in _get_url
    raise ex
  File "/home/ben/.cache/pypoetry/virtualenvs/chatgpt-telegram-bot-lQBxQO3L-py3.10/lib/python3.10/site-packages/duckduckgo_search/duckduckgo_search.py", line 82, in _get_url
    raise httpx._exceptions.HTTPError("")
httpx.HTTPError
```

I would just wrap it in a `try` and do some retry thing but I haven't actually gotten a ddg search to work, so I think this is not a transient failure. I'll try to look into cause further.

**Comment by bsima** [comment]
this `HTTPError` specifically means DDG is returning a 500, unfortunately the upstream library just gives us an empty string instead of the server's actual response, but this might have been fixed in an updated version of `duckduckgo_search` https://github.com/deedy5/duckduckgo_search/commit/edbccedaa4c8b4fe3c421d20256e08f616a8878e#diff-4abf7bf906b175e10dee218af6b116e6967c91a6798a9b519d91175e4834abfb

**Comment by bsima** [comment]
Updating to version `>=3.9.7` of duckduckgo_search seems to have resolved this :+1:

**Comment by n3d1117** [comment]
Great @bsima, could you open a PR with the version bump?

**Comment by bsima** [comment]
yeah i'll do that after dayjob stuff
