### ISSUE TITLE
module 'openai' has no attribute 'error'

### ISSUE THREAD

**Issue by rexkani** [n3d1117/chatgpt-telegram-bot#513]
i just tried to update my stack to 0.4.0 and trying to move to gpt-4-turbo, and after deployment, i'm seeing below log:

```
Traceback (most recent call last):
  File "/app/bot/main.py", line 7, in <module>
    from openai_helper import OpenAIHelper, default_max_tokens, are_functions_available
  File "/app/bot/openai_helper.py", line 83, in <module>
    class OpenAIHelper:
  File "/app/bot/openai_helper.py", line 194, in OpenAIHelper
    retry=retry_if_exception_type(openai.error.RateLimitError),
AttributeError: module 'openai' has no attribute 'error'
```

This is my .env options:

```
# BUDGET_PERIOD=monthly
# USER_BUDGETS=*
# GUEST_BUDGET=100.0
 TOKEN_PRICE=0.01
# IMAGE_PRICES=0.016,0.018,0.02
# TRANSCRIPTION_PRICE=0.006
# VISION_TOKEN_PRICE=0.01
# ENABLE_QUOTING=true
# ENABLE_IMAGE_GENERATION=true
# ENABLE_TTS_GENERATION=true
# ENABLE_TRANSCRIPTION=true
# ENABLE_VISION=true
# PROXY=http://localhost:8080
 OPENAI_MODEL=gpt-4-1106-preview
# OPENAI_BASE_URL=https://example.com/v1/
# ASSISTANT_PROMPT="You are a helpful assistant."
# SHOW_USAGE=false
# STREAM=true
 MAX_TOKENS=2400
# VISION_MAX_TOKENS=300
# MAX_HISTORY_SIZE=15
# MAX_CONVERSATION_AGE_MINUTES=180
# VOICE_REPLY_WITH_TRANSCRIPT_ONLY=true
# VOICE_REPLY_PROMPTS="Hi bot;Hey bot;Hi chat;Hey chat"
# VISION_PROMPT="What is in this image"
# N_CHOICES=1
# TEMPERATURE=1.0
# PRESENCE_PENALTY=0.0
# FREQUENCY_PENALTY=0.0
 IMAGE_MODEL=dall-e-3
 IMAGE_QUALITY=standard
# IMAGE_STYLE=natural
 IMAGE_SIZE=1024x1024
# IMAGE_FORMAT=document
# VISION_DETAIL="low"
# GROUP_TRIGGER_KEYWORD=""
# IGNORE_GROUP_TRANSCRIPTIONS=true
# IGNORE_GROUP_VISION=true
# TTS_MODEL="tts-1"
# TTS_VOICE="alloy"
# TTS_PRICES=0.015,0.030
# BOT_LANGUAGE=en
# ENABLE_VISION_FOLLOW_UP_QUESTIONS="true"
# VISION_MODEL="gpt-4-vision-preview"

```

I am the only user and my usage is very low, i believe i have not hit the limit and even if i have, i think this error is not about hitting the limit? anyone have an idea?

Thanks for your help.

**Comment by rexkani** [comment]
i have found that the error indicates that my openai_helper.py is an old version... i have already rebuilt the image and i'm confused now. let me try to look more into this issue...

**Comment by rexkani** [comment]
i have deleted everything including the volume for the stack and re-deployed. and i'm running gpt-4-vision-preview and dall-e-3 now. it was my mistake. sorry for the confusion.
