### ISSUE TITLE
Can't run the python script, I am getting an error related to unexpected keyword argument 'proxy'

### ISSUE THREAD

**Issue by jeffheartmp** [n3d1117/chatgpt-telegram-bot#578]
Traceback (most recent call last):
  File "bot/main.py", line 117, in <module>
    main()
  File "bot/main.py", line 113, in main
    telegram_bot.run()
  File "/root/chatgpt-telegram-bot/bot/telegram_bot.py", line 1051, in run
    application = ApplicationBuilder() \
  File "/root/chatgpt-telegram-bot/venv/lib/python3.8/site-packages/telegram/ext/_applicationbuilder.py", line 310, in build
    bot: Bot = self._build_ext_bot()  # build a bot
  File "/root/chatgpt-telegram-bot/venv/lib/python3.8/site-packages/telegram/ext/_applicationbuilder.py", line 280, in _build_ext_bot
    request=self._build_request(get_updates=False),
  File "/root/chatgpt-telegram-bot/venv/lib/python3.8/site-packages/telegram/ext/_applicationbuilder.py", line 260, in _build_request
    return HTTPXRequest(
  File "/root/chatgpt-telegram-bot/venv/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 189, in __init__
    self._client = self._build_client()
  File "/root/chatgpt-telegram-bot/venv/lib/python3.8/site-packages/telegram/request/_httpxrequest.py", line 224, in _build_client
    return httpx.AsyncClient(**self._client_kwargs)  # type: ignore[arg-type]
TypeError: __init__() got an unexpected keyword argument 'proxy'

**Comment by wolfich** [comment]
Do you have PROXY set in env?

**Comment by bulat15g** [comment]
@jeffheartmp Have you solved the problem? 
I am facing the same issue. 

Don't have a proxy in env.

**Comment by bulat15g** [comment]
may be it is because python 3.8 and requirements 3.9
but it worked before...

**Comment by bulat15g** [comment]
@jeffheartmp upgrade to python3.9 worked we can close issue
