### ISSUE TITLE
4000 tokens for the completion?

### ISSUE THREAD

**Issue by AlyxAbyss** [n3d1117/chatgpt-telegram-bot#77]
"I am receiving an error that I have exceeded the maximum number of tokens. In this example, I have used 152 tokens for the prompt and 4000 for the completion. Why is the completion token usage so high?"

`2023-03-18 11:25:18,531 - root - INFO - New message received from user @AlyxAbyss
2023-03-18 11:25:18,909 - openai - INFO - error_code=context_length_exceeded error_message="This model's maximum context length is 4097 tokens. Ho                      wever, you requested 4152 tokens (152 in the messages, 4000 in the completion). Please reduce the length of the messages or completion." error_par                      am=messages error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-18 11:25:18,910 - root - ERROR - This model's maximum context length is 4097 tokens. However, you requested 4152 tokens (152 in the messag                      es, 4000 in the completion). Please reduce the length of the messages or completion.
Traceback (most recent call last):
  File "/home/vicky/VickyAI/chatgpt-telegram-bot/openai_helper.py", line 49, in get_chat_response
    response = openai.ChatCompletion.create(
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4152 tokens (152 in the messages, 400                      0 in the completion). Please reduce the length of the messages or completion.`

**Comment by n3d1117** [comment]
Hi @AlyxAbyss can you share what was your input and how long was your conversation?

Also, are you using latest version?

**Comment by AlyxAbyss** [comment]
I have now used /reset and started a new conversation with the text "Hi. What is your name?"

Immediately after that, I receive the following messages again in the terminal:


`2023-03-18 13:24:21,212 - telegram.ext._application - INFO - Application started
2023-03-18 13:24:26,589 - root - INFO - Resetting the conversation for user @AlyxAbyss...
2023-03-18 13:24:58,790 - root - INFO - New message received from user @AlyxAbyss
2023-03-18 13:24:59,456 - openai - INFO - error_code=context_length_exceeded error_me
![Screenshot_20230318-132519_Telegram](https://user-images.githubusercontent.com/82916181/226106147-2cf2beaa-eef4-453f-8524-e2e58515835c.jpg)
ssage="This model's maximum context length is 4097 tokens. However, you requested 4122 tokens (25 in the messages, 4097 in the completion). Please reduce the length of the messages or completion." error_param=messages error_type=invalid_request_error message='OpenAI API error received' stream_error=False
2023-03-18 13:24:59,457 - root - ERROR - This model's maximum context length is 4097 tokens. However, you requested 4122 tokens (25 in the messages, 4097 in the completion). Please reduce the length of the messages or completion.
Traceback (most recent call last):
  File "/home/vicky/VickyAI/chatgpt-telegram-bot/openai_helper.py", line 49, in get_chat_response
    response = openai.ChatCompletion.create(
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/vicky/.local/lib/python3.9/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, you requested 4122 tokens (25 in the messages, 4097 in the completion). Please reduce the length of the messages or completion.

`

**Comment by mithew** [comment]
MAX_TOKENS=4000

Did you make this setting in the .env？

**Comment by AlyxAbyss** [comment]
"I found the error. I had entered the entry "MAX_TOKENS=4000" in the .env file. However, it seems to be too high. I reduced the entry to 2000 and now the error is resolved."
