### ISSUE TITLE
Failure in execute main.py shows TimeOut ,how can I slove that? Thanks.

### ISSUE THREAD

**Issue by Underson888** [n3d1117/chatgpt-telegram-bot#9]
:~/chatgpt-telegram-bot# python main.py
Debugger enabled on OpenAIAuth
Logging in...
Debugger enabled on OpenAIAuth
Beginning auth process
Beginning part two
Beginning part three
Beginning part four
Beginning part five
Beginning part six
Beginning part seven
Request went through
Response code is 302
New state found
Beginning part eight
Beginning part nine
SUCCESS
Part eight called
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/anyio/streams/tls.py", line 130, in _call_sslobject_method
    result = func(*args)
  File "/usr/lib/python3.10/ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/anyio/streams/tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 66, in start_tls
    with anyio.fail_after(timeout):
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 64, in start_tls
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 183, in do_request
    res = await self._client.request(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/chatgpt-telegram-bot/main.py", line 32, in <module>
    main()
  File "/root/chatgpt-telegram-bot/main.py", line 28, in main
    telegram_bot.run()
  File "/root/chatgpt-telegram-bot/telegram_bot.py", line 125, in run
    application.run_polling()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/ext/_application.py", line 670, in run_polling
    return self.__run(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/ext/_application.py", line 858, in __run
    raise exc
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/ext/_application.py", line 847, in __run
    loop.run_until_complete(self.initialize())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/ext/_application.py", line 357, in initialize
    await self.bot.initialize()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 252, in initialize
    await super().initialize()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/_bot.py", line 499, in initialize
    await self.get_me()
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 1639, in get_me
    return await super().get_me(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/_bot.py", line 313, in decorator
    result = await func(*args, **kwargs)  # skipcq: PYL-E1102
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/_bot.py", line 644, in get_me
    result = await self._post(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/_bot.py", line 395, in _post
    return await self._do_post(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 306, in _do_post
    return await super()._do_post(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/_bot.py", line 426, in _do_post
    return await request.post(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 167, in post
    result = await self._request_wrapper(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 290, in _request_wrapper
    raise exc
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 276, in _request_wrapper
    code, payload = await self.do_request(
  File "/root/.local/share/virtualenvs/chatgpt-telegram-bot-IagjQVk0/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 200, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out

**Comment by Underson888** [comment]
> 

Yes, but still failed

**Comment by xmbhjQAQ** [comment]
OKEY... I have the same problem Once the socks5 proxy is used, it will be stuck in "Part eight called". However, when I use the global proxy on the router, this will not happen. It is strange

**Comment by Underson888** [comment]
> OKEY... I have the same problem Once the socks5 proxy is used, it will be stuck in "Part eight called". However, when I use the global proxy on the router, this will not happen. It is strange

Can you share your proxier?I use clash and set it as global, but it still failed.

**Comment by n3d1117** [comment]
Closing this because it seems to be a proxy issue, see https://github.com/n3d1117/chatgpt-telegram-bot/issues/10 for proxy support
